version: '3'
services:
  app:
    build:
      context: .
      args:
        RAILS_ENV: ${RAILS_ENV:-development}
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    networks:
      - local

  muffet:
    depends_on:
      - app
    image: raviqqe/muffet
    networks:
      - local

networks:
  local:
    driver: bridge

